/* empty css                      */import{S as f,N as m}from"./assets/vendor-Sm41FR0M.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&c(r)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".gallery-swiper");n&&new f(n,{modules:[m],loop:!0,direction:"horizontal",slideClass:"gallery-swiper-slide",wrapperClass:"gallery-swiper-wrapper",navigation:{nextEl:".custom-navigation .custom-next",prevEl:".custom-navigation .custom-prev"},breakpoints:{374:{slidesPerView:1.2,spaceBetween:20,centeredSlides:!1},1439:{slidesPerView:3,spaceBetween:20,centeredSlides:!1}}})});document.querySelectorAll(".faq-acc-el-trigger").forEach(n=>{n.addEventListener("click",()=>{const o=n.closest(".faq-acc-el"),s=o.querySelector(".faq-acc-el-descr-frame"),c=o.querySelector(".faq-img");o.classList.contains("open")?(o.classList.remove("open"),c==null||c.classList.remove("rotated"),s&&(s.style.maxHeight="0")):(o.classList.add("open"),c==null||c.classList.add("rotated"),s&&(s.style.maxHeight=s.scrollHeight+"px"))})});const l=document.querySelectorAll(".navigation-item");l.forEach(n=>{n.addEventListener("click",function(o){o.preventDefault(),l.forEach(s=>s.classList.remove("active")),this.classList.add("active")})});document.addEventListener("DOMContentLoaded",function(){const n=document.getElementById("cookie-popup"),o=document.getElementById("accept-cookies"),s=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(n.style.display="block"),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),n.style.display="none"}),s.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),n.style.display="none"})});document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll('a[href^="#"]').forEach(n=>{n.addEventListener("click",function(o){o.preventDefault();const s=this.getAttribute("href").substring(1),c=document.getElementById(s);if(c){const t=c.offsetTop-90;window.scrollTo({top:t,behavior:"smooth"})}})})});document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".menu-button"),o=n.querySelector(".icon"),s=document.querySelector(".modal"),c=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const r=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#E1CC6D" />
  <path d="M5.625 7.125H18.375M5.625 16.125H18.375M5.625 11.625H18.375" stroke="#F1F1F1" stroke-linecap="round" />
</svg>
    `,d=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#E1CC6D" />
  <path d="M5.25 5.25L12 12M12 12L5.25 18.75M12 12L18.75 18.75M12 12L18.75 5.25" stroke="#F1F1F1" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;n.addEventListener("click",()=>{t=!t,o.innerHTML=t?d:r,t?a():i()}),c.forEach(p=>p.addEventListener("click",()=>{i(),o.innerHTML=r,t=!1})),window.addEventListener("scroll",u);function a(){s.style.display="block"}function i(){s.style.display="none"}function u(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});
//# sourceMappingURL=index.js.map
